### ISSUE TITLE
camera-controls package removed from github

### ISSUE THREAD

**Issue by Xqua** [icosa-foundation/gallery-viewer#13]
Hey, there's a bug on install due to the npm package for camera-controls not being available on GitHub anymore:

```
npm install --save icosa-viewer
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/mikeskydev/camera-controls.git
npm ERR! 
npm ERR! remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
npm ERR! remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
npm ERR! fatal: Authentication failed for 'https://github.com/mikeskydev/camera-controls.git/'
npm ERR! 
npm ERR! exited with error code: 128
```

This is due to the package-lock that is pointing to the github link, yet that is dead.

**Comment by mikeskydev** [comment]
Hello, please update to v0.7.1 (latest at the time of writing) which no longer has this dependency. My custom branch of `camera-controls` is no longer needed due to modifications in the main repository. Thanks!
